# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-formtools
  version: '2.7'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 52b30c08571108023937e4b5d96a5cc35282ff0a2e51630aeea00e27d723d3ac

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.2
    - setuptools-scm
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - django >=5.2
tests:
  - python:
      imports:
        - formtools
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: A set of high-level abstractions for Django forms
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://django-formtools.readthedocs.io/en/latest/
  repository: https://github.com/jazzband/django-formtools

extra:
  recipe-maintainers:
    - rxm7706
